name: CI/CD Monorepo FastAPI Services

on:
  push:
    branches:
      - main

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect services from commit message
        id: set-matrix
        run: |
          echo "Getting commit message..."
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Extract service names like "service_x" before "@"
          SERVICES=$(echo "$COMMIT_MSG" | grep -oE 'service_[a-zA-Z0-9_-]+(?=@)' | sort -u)

          if [ -z "$SERVICES" ]; then
            echo "No services found in commit message."
            echo "matrix=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          MATRIX_JSON=$(printf '%s\n' $SERVICES | jq -R . | jq -s '{"service": .}')
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "Detected matrix: $MATRIX_JSON"

  build-and-deploy:
    needs: detect-services
    if: needs.detect-services.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-services.outputs.matrix)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (mock)
        run: echo "Skipping login (mock)"

      - name: Build Docker image
        run: |
          echo "Building service: ${{ matrix.service }}"
          docker build -t ${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Docker image (mock)
        run: echo "Skipping push (mock)"

      - name: Deploy to Azure Container Apps (mock)
        run: echo "Deploying ${{ matrix.service }} (mock)"
