name: CI/CD Pipeline

on:
  push:
    tags:
      - 'build-*'  
jobs:
  build-service-a:
    if: startsWith(github.ref, 'refs/tags/build-service-a') || startsWith(github.ref, 'refs/tags/build-all')
    name: Build Service A
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for service_a
        run: docker build -t service_a:latest ./service_a

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          docker tag service_a:latest nhatnam0608/service_a:latest
          docker push nhatnam0608/service_a:latest


  build-service-b:
    if: startsWith(github.ref, 'refs/tags/build-service-b') || startsWith(github.ref, 'refs/tags/build-all')
    name: Build Service B
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for service_b
        run: docker build -t service_b:latest ./service_b

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          docker tag service_b:latest nhatnam0608/service_b:latest
          docker push nhatnam0608/service_b:latest
